feat(mindmap): #EV-305 add duplication for mindmap
OPEN-ENT-NG/mindmap pull request #12
Opened 2022-06-09 12:56 UTC by vava56754

## Describe your changes
Ajout de la duplication qui permet de dupliquer ses cartes mentales dans le dossier où elles se trouvent et  aussi dupliquer les cartes mentales partagées si on en possède le droit
## Checklist tests
Dupliquer la carte mentale, elle se duplique dans le dossier de l'original.
Dupliquer la carte mentale, elle possède les mêmes informations que la carte original.
Dupliquer la carte mentale qui est partagée, la carte mentale dupliqué appartient a celui qui la duplique.
## Issue ticket number and link
EV-305: https://entsupport.gdapublic.fr/projects/EV/issues/EV-305
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-06-09 14:20 UTC, JinDouang commented on src/main/resources/public/ts/services/mindmap.service.ts
> +        return await http.post(`/mindmap/duplicate/${id}`);
à revoir l'endpoint

2022-06-09 14:23 UTC, JinDouang commented
Il manque la doc API à renseigner

2022-06-09 14:25 UTC, BastienBenard reviewed
tu peux faire des tests sur mindmap.service.ts et MindmapServiceImpl.java, si tu es pas dans la sauce.

2022-06-20 06:38 UTC, JinDouang requested changes

2022-06-20 06:38 UTC, JinDouang commented on src/main/resources/public/ts/services/mindmap.service.ts
> +        return await http.post(`/mindmap/${id}/duplicate?folderTarget=${folderParentId}`);
le await n'est pas nécessaire

2022-06-20 06:38 UTC, JinDouang commented on src/main/java/net/atos/entng/mindmap/service/impl/MindmapServiceImpl.java
> +            }
et si ça fail ?

2022-06-20 06:38 UTC, JinDouang commented on src/main/java/net/atos/entng/mindmap/service/impl/MindmapServiceImpl.java
> +        Promise<JsonObject> promise = Promise.promise();
au dessus la déclaration de préférence

2022-06-20 06:38 UTC, JinDouang commented on src/main/java/net/atos/entng/mindmap/controllers/MindmapController.java
> +        String folderParentId = request.params().get("folderTarget");
Magic string ?

2022-06-20 06:38 UTC, JinDouang commented on src/main/java/net/atos/entng/mindmap/controllers/MindmapController.java
> +        mindmapService.getMindmap(id).onFailure(error -> badRequest(request))
Tu avais besoin de le modifier ?

2022-06-20 06:38 UTC, JinDouang commented on src/main/java/net/atos/entng/mindmap/service/impl/MindmapServiceImpl.java
> +                .onSuccess(resCreate -> promise.complete())
Que veux-tu retourner ?
Si tu veux rien retourner utilise Void plutôt que JsonObject

2022-06-20 06:38 UTC, JinDouang commented on src/main/java/net/atos/entng/mindmap/service/impl/MindmapServiceImpl.java
> +                    String message = String.format("[Mindmap@%s::duplicateMindmap] Failed to duplicate the mindmap: %s",
tu fail pas ta promise dans ce cas ? Ton API ne répondra jamais..

2022-06-20 12:00 UTC, JinDouang requested changes

2022-06-20 12:00 UTC, JinDouang commented on src/main/java/net/atos/entng/mindmap/service/impl/MindmapServiceImpl.java
> +                promise.fail(message);
log error ?

2022-06-20 12:00 UTC, JinDouang commented on src/main/java/net/atos/entng/mindmap/service/impl/MindmapServiceImpl.java
> +                promise.fail(message);
promise.fail error.getMessage plutôt que ton message

2022-06-20 12:00 UTC, JinDouang commented on src/main/java/net/atos/entng/mindmap/service/impl/MindmapServiceImpl.java
> +                        this.getClass().getSimpleName(), event.left().getValue());
log ?

2022-06-20 12:00 UTC, JinDouang commented on src/main/java/net/atos/entng/mindmap/service/impl/MindmapServiceImpl.java
> +                        this.getClass().getSimpleName(), event.left().getValue());
promise.fail error.getMessage plutôt que ton message

2022-06-20 12:56 UTC, JinDouang approved these changes

2022-06-20 13:05 UTC, merged