chore(libs): update typescript to 4.8.4, delete package-lock.json
OPEN-ENT-NG/mindmap pull request #22
Opened 2022-12-16 15:15 UTC by Matiyeu

## Describe your changes
update typescript to 4.8.4
delete package-lock.json and add to .gitignore
fix ./build.sh buildNode

## Checklist tests

./build.sh buildNode testNode :white_check_mark:

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-12-16 15:41 UTC, sjollois approved these changes

2022-12-16 15:42 UTC, sjollois commented
Tu pourrais rajouter le wokflows github de test de buildNode non ?

2022-12-16 16:02 UTC, JinDouang requested changes

2022-12-16 16:02 UTC, JinDouang commented on package.json
> +    "typescript": "4.8.4",
Base toi sur ce commit niveau version pour être ISO : https://github.com/OPEN-ENT-NG/geogebra/commit/3cb2eae2c0e02c5a6544d1331affe8f2354cf817#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R21

2022-12-19 08:39 UTC, qpic-cgi approved these changes

2022-12-19 16:33 UTC, JinDouang approved these changes

2022-12-19 16:35 UTC, merged